version: '3.8'

services:
  # Development PostgreSQL
  postgres-dev:
    image: postgres:15-alpine
    container_name: marvel-postgres-dev
    environment:
      POSTGRES_DB: marvel_db
      POSTGRES_USER: marvel_user
      POSTGRES_PASSWORD: marvel_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marvel_user -d marvel_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data: